#!/usr/bin/env python3
"""
CatalystOS Agent — Abegbe Agboola Chambers Legal Automation
Executes skills, chains AI tasks, handles legal document generation.
"""

from http.server import HTTPServer, BaseHTTPRequestHandler
import json
import urllib.parse
import datetime
import os

PORT = 5000

LEGAL_TEMPLATES = {
    "affidavit": """AFFIDAVIT

IN THE {court} OF THE {state} STATE
HOLDEN AT {location}

{suit_number}

BETWEEN

{plaintiff}                                    PLAINTIFF/APPLICANT

AND

{defendant}                                    DEFENDANT/RESPONDENT

AFFIDAVIT IN SUPPORT OF {motion_type}

I, {deponent_name}, {deponent_description}, do hereby make oath and state as follows:

1. I am the {deponent_role} in this matter and I am conversant with the facts deposed to herein.

2. {fact_1}

3. {fact_2}

4. {fact_3}

5. I depose to this affidavit in good faith believing the contents herein to be true and correct to the best of my knowledge.

SWORN TO at {location}
this _____ day of _____________, 2026

___________________________
DEPONENT

Before me:

___________________________
COMMISSIONER FOR OATHS

---
Generated by CatalystOS | Abegbe Agboola Chambers | Lagos, Nigeria
""",

    "motion": """MOTION

IN THE {court} OF THE {state} STATE
HOLDEN AT {location}

{suit_number}

BETWEEN

{plaintiff}                                    PLAINTIFF/APPLICANT

AND

{defendant}                                    DEFENDANT/RESPONDENT

MOTION ON NOTICE

TAKE NOTICE that on _____ day of _____________, 2026, the Applicant shall apply to this Honourable Court for the following reliefs:

1. {relief_1}

2. {relief_2}

3. {relief_3}

4. Such further or other orders as this Honourable Court may deem fit to make in the circumstances of this case.

AND TAKE FURTHER NOTICE that the grounds for this application are as contained in the Affidavit in Support sworn to by {deponent_name} and filed along with this motion.

DATED this _____ day of _____________, 2026.

___________________________
Applicant/Applicant's Counsel
Abegbe Agboola Chambers
Ikoyi, Lagos

---
Generated by CatalystOS | Abegbe Agboola Chambers | Lagos, Nigeria
""",

    "demand_letter": """WITHOUT PREJUDICE

{date}

{recipient_name}
{recipient_address}

Dear {salutation},

RE: {subject}

We are solicitors to {client_name} (hereinafter referred to as "our Client") on whose instructions we write to you.

Our Client has instructed us that {situation_description}.

By this letter, we hereby give you {notice_period} DAYS' notice to {demand}. Failure to comply with the above demand within the stated period shall compel our Client to take all necessary legal steps to enforce its rights, including but not limited to instituting legal proceedings against you in a court of competent jurisdiction, and you shall bear all costs incidental thereto.

PLEASE GOVERN YOURSELF ACCORDINGLY.

Yours faithfully,

___________________________
For: ABEGBE AGBOOLA CHAMBERS

---
Generated by CatalystOS | Abegbe Agboola Chambers | Lagos, Nigeria
"""
}


class CatalystAgentHandler(BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

        if path == "/health":
            resp = {"status": "online", "agent": "CatalystOS", "timestamp": datetime.datetime.now().isoformat()}
        elif path == "/templates":
            resp = {"templates": list(LEGAL_TEMPLATES.keys())}
        else:
            resp = {"error": "Unknown endpoint", "available": ["/health", "/templates", "/generate"]}

        self.wfile.write(json.dumps(resp).encode())

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length)
        try:
            data = json.loads(body)
        except Exception:
            data = {}

        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()

        if path == "/generate":
            template_name = data.get("template", "affidavit")
            fields = data.get("fields", {})
            template = LEGAL_TEMPLATES.get(template_name, LEGAL_TEMPLATES["affidavit"])

            # Fill in defaults for missing fields
            defaults = {
                "court": "HIGH COURT",
                "state": "LAGOS",
                "location": "LAGOS",
                "suit_number": "SUIT NO: LD/HC/____________/2026",
                "plaintiff": "[PLAINTIFF NAME]",
                "defendant": "[DEFENDANT NAME]",
                "motion_type": "[MOTION TYPE]",
                "deponent_name": "[DEPONENT NAME]",
                "deponent_description": "[DESCRIPTION]",
                "deponent_role": "[ROLE]",
                "fact_1": "[FACT 1]",
                "fact_2": "[FACT 2]",
                "fact_3": "[FACT 3]",
                "relief_1": "[RELIEF 1]",
                "relief_2": "[RELIEF 2]",
                "relief_3": "[RELIEF 3]",
                "recipient_name": "[RECIPIENT NAME]",
                "recipient_address": "[RECIPIENT ADDRESS]",
                "salutation": "Sir/Madam",
                "subject": "[SUBJECT MATTER]",
                "client_name": "[CLIENT NAME]",
                "situation_description": "[DESCRIBE SITUATION]",
                "notice_period": "14",
                "demand": "[STATE DEMAND]",
                "date": datetime.datetime.now().strftime("%d %B, %Y"),
            }
            defaults.update(fields)

            try:
                result = template.format(**defaults)
            except KeyError as e:
                result = f"Template error — missing field: {e}"

            # Save to workspace
            filename = f"{template_name}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
            save_path = os.path.join(os.path.dirname(__file__), "..", "..", "workspace", filename)
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            with open(save_path, "w") as f:
                f.write(result)

            resp = {
                "status": "success",
                "template": template_name,
                "document": result,
                "saved_as": filename
            }
        else:
            resp = {"error": "Unknown endpoint"}

        self.wfile.write(json.dumps(resp).encode())

    def log_message(self, format, *args):
        print(f"[CatalystAgent] {self.address_string()} — {format % args}")


if __name__ == "__main__":
    print(f"🐍 CatalystOS Agent starting on port {PORT}...")
    print(f"⚖️  Abegbe Agboola Chambers Legal Automation ONLINE")
    print(f"📋 Templates: {', '.join(LEGAL_TEMPLATES.keys())}")
    print(f"🌐 Health check: http://localhost:{PORT}/health")
    server = HTTPServer(("0.0.0.0", PORT), CatalystAgentHandler)
    server.serve_forever()
